/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CustomHealthCheck,
  CustomHealthCheckInterface,
} from "../CustomHealthCheck";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "profit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "loss",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "debtPayment",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "debtOutstanding",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "callerStrategy",
        type: "address",
      },
    ],
    name: "check",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class CustomHealthCheck__factory {
  static readonly abi = _abi;
  static createInterface(): CustomHealthCheckInterface {
    return new utils.Interface(_abi) as CustomHealthCheckInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CustomHealthCheck {
    return new Contract(address, _abi, signerOrProvider) as CustomHealthCheck;
  }
}
